services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PGURL: "postgres://postgres:postgres@db:5432/restaurantes"

  db:
    build: ./postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurantes

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      BACKEND_URL: "http://backend:8000/api/v1"
